version: 1.0.{build}
# skip_non_tags: true
image: Visual Studio 2017
install:
- ps: Install-Product node ''
- cmd: npm install
build_script:
- ps: node build --xpi --7z
artifacts:
- path: dist.unsigned.xpi
